# 61e034d65a0367ef4bb924ca546a8c18
# Do not modify this file!  It was generated by ‘nixos rekey’ 
# and may be overwritten by future invocations. 
# Please add public keys to /etc/nixos/secrets/keys/*.pub 
rec {

  users.me_laptop = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMUkQkJn9u/agQK7rRoWSKV8jw3Ykj1Gdg5ovAkXyYcc8fDQWdaFc7ldsCPStoiSyKft/Y9+yZLp9Ieasy6DCGZH3a5fDDa3CfC4v6nETHDeei+fCnbHpaAkNSBe0ocRXhUzNRxWYy0tdqHrRzt21jVlX6MuUwlZCV4nNuXAoB8F34z7bucb2sFv8ELmuw2fob1tvJdZ+sbCSA6TWBLGadifn6bNmslTcDTm4HETXPbA+KtnzTBatwVVAzkqJ6vzq5fz1lhZXPux1B90yD+SxravKx8+ln/DtvFjdR1uMFXh5VKkUsISod5T73qWeriXddiw8BSbnOrRxoxm03PGKy1zDWW2ZUJCKIBNRmUmgc02PVb13ypKZp3yz3RGCahQGveiJ+hlSxEcQPi9q5PNTSeqoKi7/f6gCnPO667mxqeNmMQMPqCF1zBOkQ1Ue00dlRUUCoiwpc7BkWagux8Pg/HNZwHON4AQljiP+fAjEb+gjLcM28MIZUbY7fyTW/u70= Laptop";
  users.me = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaBClteYpmg2puo+fVjz8GgcTC1EyLVmoJxqOW6mxw92IPM3SZ71Ksu/Lm7SRDEAJdfqMqBhExbAvKJcC+EGwErXJcTC8V8+EWJfmQaZXvt5QynLPi6d1EbzB5n042j1dZOHQQg8wlygwPQLcEzHwF9QGQCN7iz/rpMeuSQ/Oxh0wT4m/7gPbdfQB4Dm9r2LRLQQ5zmTOD4ErNaQC/w8K4ecBirPd8X3lZYC+S9kO7x3w02vdWPXq5usipbXU3lv9JtWEhxvg0fNSGrhpClqULH2gGaUq2PKbt1iH+GTWcZv7cQChkhlNlwjTvhkS6/mXgSqGNmWfC/Ulcv56V4g+edLZuga3KtYPA9c/NrIbdjSRuJL18THwDlbvqnwr155zaEP6p/KyH/r9kY+mhlclXUOo46jO2rsWHzCb7WZz13hSXU4WVi5aqNvWf0lZIfO54k9nU6DeI7H4AuIxkNRS7bIJJoNjpi8rsTL80Ri8xt2e9TAjE/UlSlELbeMNfp48=";
  users.me_work = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP5Kh7FNQXVoP88pjaxmSnlp4jL+xtf90ODcvmbh8rgz";
  users.all = [ users.me_laptop users.me users.me_work ];

  systems.bender = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG2cTFLpZ3cFnHMrpCCcCFi7/CuOv8h2gvCfhRLTwtve";
  systems.morbo = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPF+CWtqtcb8BM5COoxRdm9B/3oj12Jch62WErsfYkLQ";
  systems.nibbler = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDkagDgX7kRNPywtlLbjsIHjwaddUKqVOVPtC2f+mhMf";
  systems.all = [ systems.bender systems.morbo systems.nibbler ];

  all = users.all ++ systems.all;

}
