# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, lib, modulesPath, ... }:

{
  imports =
    [
      # Include the container-specific autogenerated configuration.
      ./hardware-configuration.nix
    ];

  # Allow vscode-remote to work on this system
  programs.nix-ld.enable = true;

  modules.tailscale.enable = true;
  modules.ddns.enable = true;
  
  # Services
  modules.whoami.enable = true;
  modules.cockpit.enable = true;

  modules.traefik = {
    extraInternalHostNames = [ "sonarr.zz" ];
  };

  modules.sonarr = {
    enable = true;  
    name = "sonarr.zz";
  };
}