# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, inputs, outputs, ... }:

{
  imports = [
    # Need to load some defaults for running in an lxc container.
    # This is explained in:
    # https://github.com/nix-community/nixos-generators/issues/79
    "${inputs.nixpkgs}/nixos/modules/virtualisation/lxc-container.nix"
  ];
  # This doesn't do _everything_ we need, because `boot.isContainer` is
  # specifically talking about light-weight NixOS containers, not LXC. But it
  # does at least gives us so
  boot.isContainer = true;

  # Set your system kind (needed for flakes)
  nixpkgs.hostPlatform = "x86_64-linux";
}
