# Do not modify this file!  It was generated by ‘nixos secrets’ 
# and may be overwritten by future invocations. 
# Please add age files to /etc/nixos/secrets/files/*.age 
{

  alphanumeric-secret = ./alphanumeric-secret.age;
  basic-auth = ./basic-auth.age;
  blobfuse-yaml = ./blobfuse-yaml.age;
  ca-key = ./ca-key.age;
  cloudflare-env = ./cloudflare-env.age;
  ocis-env = ./ocis-env.age;
  password = ./password.age;
  password-hash = ./password-hash.age;
  rclone-conf = ./rclone-conf.age;
  restic-azure-env = ./restic-azure-env.age;
  traefik-env = ./traefik-env.age;

}
