name: "build"
on:
  pull_request:
  push:
jobs:
  build-bootstrap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        name: suderman
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.bootstrap.config.system.build.toplevel
  build-sol:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        name: suderman
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.sol.config.system.build.toplevel
  build-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        name: suderman
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.hub.config.system.build.toplevel
  build-lux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        name: suderman
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.lux.config.system.build.toplevel
  build-pom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        name: suderman
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.pom.config.system.build.toplevel
  build-eve:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        name: suderman
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.eve.config.system.build.toplevel
