name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check
    - run: nix build .#nixosConfigurations.bootstrap.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.min.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.cog.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.sol.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.lab.config.system.build.toplevel
